import { ASSIGNMENTS as API_ASSIGNMENTS } from './apiEndPoints'

export const ASSIGNMENT_BY_ID = API_ASSIGNMENTS.BY_ID
export const ASSIGNMENT_SUBMIT = API_ASSIGNMENTS.SUBMIT
export const ASSIGNMENT_GRADE = API_ASSIGNMENTS.GRADE
export const ASSIGNMENTS = API_ASSIGNMENTS.LIST
